# fly.toml app configuration file generated for fly-nginx-dev on 2024-01-21T01:42:34+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fly-nginx-dev"
primary_region = "sin"

kill_signal = "SIGTERM"
kill_timeout = 5

[build]

[deploy]
  strategy = "bluegreen"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    port = 80
  [[services.http_checks]]
    grace_period = "5s"
    interval = "5s"
    restart_limit = 0
    timeout = "10s"
    path = "/health"
    protocol = "http"
    [services.http_checks.headers]
      User-Agent = "service_http_check"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]

[[services]]
  internal_port = 8443
  protocol = "tcp"
  [[services.ports]]
    port = 443
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
